#!/bin/bash

setxkbmap hr
setxkbmap -option terminate:ctrl_alt_bksp
xset r rate 400

# libinput touchpad
#xinput set-prop 12 292 1
#xinput set-prop 12 288 1
#xinput set-prop 'SynPS/2 Synaptics TouchPad' 292 1
#xinput set-prop 'SynPS/2 Synaptics TouchPad' 288 1

# synaptics touchpad
synclient PalmDetect=1
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient CoastingSpeed=0
syndaemon -i 0.4 -t -K -R &

compton -b
nm-applet &
pasystray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(ssh-agent)

exec i3

