#!/bin/bash

# synaptics touchpad
synclient PalmDetect=1
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient CoastingSpeed=0
syndaemon -i 0.4 -t -K -R &
setxkbmap -option terminate:ctrl_alt_bksp
xset r rate 400
picom -b &
nm-applet &
pasystray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(ssh-agent)

