#!/bin/bash

setxkbmap hr

# libinput touchpad
#xinput set-prop 12 292 1
#xinput set-prop 12 288 1
#xinput set-prop 'SynPS/2 Synaptics TouchPad' 292 1
#xinput set-prop 'SynPS/2 Synaptics TouchPad' 288 1

# synaptics touchpad
synclient PalmDetect=1
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
syndaemon -i 0.4 -t -K -R &

compton -CGb --no-fading-openclose

eval $(ssh-agent)

exec i3

